// Precomputes the canned correction-loop demo scenario and caches results to
// data/correction-demo.json. Modeled on scripts/precompute.ts.
//
// Scenario: reviewer corrects check-handwritten — sender was read as
// "Coastal Credit Union" (the drawee bank) but the actual sender is "R. Delgado".
// That correction is injected as a few-shot exemplar when re-extracting the
// other review-queue items.
//
// Run: npm run precompute:correction
import { readFileSync, writeFileSync } from "node:fs";
import { extractFromImage } from "../lib/extract.ts";
import type { CorrectionExemplar, RawResult } from "../lib/extract.ts";
import type { ExtractionRecord } from "../lib/types.ts";
import { routeExtraction } from "../lib/types.ts";

const MODEL = "claude-haiku-4-5";
const samplesPath = new URL("../public/samples/", import.meta.url).pathname;
const extractionsPath = new URL("../data/extractions.json", import.meta.url).pathname;
const outPath = new URL("../data/correction-demo.json", import.meta.url).pathname;

const hasKey = !!(process.env.ANTHROPIC_API_KEY || process.env.OPENROUTER_API_KEY);
if (!hasKey) {
  console.error("No API key found. Set ANTHROPIC_API_KEY or OPENROUTER_API_KEY.");
  console.error("Without a key, data/correction-demo.json contains simulated output.");
  process.exit(1);
}

const extractions: ExtractionRecord[] = JSON.parse(readFileSync(extractionsPath, "utf8"));
const byId = new Map<string, ExtractionRecord>();
for (const r of extractions) if (r.model === MODEL) byId.set(r.sampleId, r);

// The correction the reviewer made on check-handwritten.
const exemplar: CorrectionExemplar = {
  sampleLabel: "Handwritten check",
  field: "sender",
  before: "Coastal Credit Union",
  after: "R. Delgado",
};

// Re-run the other review-queue items (not the corrected item itself).
// check-handwritten was the doc being corrected. legal-service, de-franchise,
// irs-notice are always-review. utility-bill is the interesting one: it was at
// 0.89 confidence (just under the 0.90 bar) and may benefit from the exemplar.
const rerunIds = ["utility-bill", "legal-service", "de-franchise", "irs-notice"];

interface DemoResult {
  sampleId: string;
  before: { overallConfidence: number; recommendedAction: string };
  after: {
    extraction: object;
    overallConfidence: number;
    recommendedAction: string;
    latencyMs: number;
  };
  fromCache: boolean;
}

const results: DemoResult[] = [];

for (const sampleId of rerunIds) {
  const prior = byId.get(sampleId);
  if (!prior) { console.log(`skip ${sampleId} — no cached extraction`); continue; }
  process.stdout.write(`re-extracting ${sampleId} with exemplar ... `);
  try {
    const b64 = readFileSync(`${samplesPath}${sampleId}.png`).toString("base64");
    const r: RawResult = await extractFromImage(b64, "image/png", MODEL, [exemplar]);
    const routeBefore = routeExtraction(prior.extraction).route;
    const routeAfter = routeExtraction(r.extraction).route;
    console.log(
      `ok ${r.latencyMs}ms conf=${prior.extraction.overallConfidence}→${r.extraction.overallConfidence} route=${routeBefore}→${routeAfter}`
    );
    results.push({
      sampleId,
      before: {
        overallConfidence: prior.extraction.overallConfidence,
        recommendedAction: prior.extraction.recommendedAction,
      },
      after: {
        extraction: r.extraction,
        overallConfidence: r.extraction.overallConfidence,
        recommendedAction: r.extraction.recommendedAction,
        latencyMs: r.latencyMs,
      },
      fromCache: false,
    });
  } catch (err) {
    console.log("FAILED:", (err as Error).message.slice(0, 120));
  }
}

const output = {
  _note: "Real model output. Generated by npm run precompute:correction.",
  _scenario:
    "Reviewer corrects check-handwritten sender from 'Coastal Credit Union' to 'R. Delgado'. Re-extraction runs on the other review-queue items with that correction as a few-shot exemplar.",
  correction: {
    sampleId: "check-handwritten",
    field: "sender",
    before: "Coastal Credit Union",
    after: "R. Delgado",
  },
  results,
};

writeFileSync(outPath, JSON.stringify(output, null, 1));
console.log(`\nwrote ${results.length} results -> data/correction-demo.json`);
